#index:
#    path: /
#    controller: App\Controller\DefaultController::index
about:
    path:         /about
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/about.html.twig

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
