#index:
#    path: /
#    controller: App\Controller\DefaultController::index
about:
    path:         /about
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/about.html.twig

services:
    path:         /services
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/services.html.twig

blog:
    path:         /blog
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/blog.html.twig



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
